#Structure
site_name: Rémi Bourgeois's blog
theme:
  name: readthedocs
  #custom_dir: overrides
nav:
  - About: about.md
  - Home: index.md
  - Posts:
      - Five basic performance advice for porting kernels to the GPU: posts/post1.md
      - The cost of communications: posts/post2.md
      - (WIP) Testing mixed precision at runtime with verrou: posts/post3.md
      - (WIP) Scheduling different jobs on the same runner with Gitlab's CI: posts/post4.md
      - (WIP) My GPU collection: posts/post5.md

#Latex
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # allows inline $...$ and display $$...$$ math
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

#last edited
plugins:
  - search
  - git-revision-date-localized:
      type: timeago  # or "full" for full date format
      fallback_to_build_date: true