#Structure
site_name: My Blog
theme:
  name: readthedocs
  custom_dir: overrides
nav:
#  - Home: index.md
#  - About: about.md
  - Posts:
      - Six basic performance advices for porting kernels to the GPU: posts/post1.md
      - The cost of communications: posts/post2.md

#Latex
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # allows inline $...$ and display $$...$$ math
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

